"""empty message

Revision ID: 1a167de09a80
Revises: 4505fc8bddbe
Create Date: 2015-08-20 13:59:04.657526

"""

# revision identifiers, used by Alembic.
revision = '1a167de09a80'
down_revision = '4505fc8bddbe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recommendations', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recommendations')
    ### end Alembic commands ###
