"""empty message

Revision ID: 2483c5c4e561
Revises: 1e9bc48e4a5d
Create Date: 2015-08-08 21:49:59.087744

"""

# revision identifiers, used by Alembic.
revision = '2483c5c4e561'
down_revision = '1e9bc48e4a5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'movie_id')
    ### end Alembic commands ###
