"""empty message

Revision ID: 310eaf7897af
Revises: 56a6e00faec8
Create Date: 2015-08-13 16:25:26.122705

"""

# revision identifiers, used by Alembic.
revision = '310eaf7897af'
down_revision = '56a6e00faec8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ratings', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ratings')
    ### end Alembic commands ###
