"""empty message

Revision ID: 3713c13beff0
Revises: 45592b7c4a13
Create Date: 2015-08-10 13:39:10.078414

"""

# revision identifiers, used by Alembic.
revision = '3713c13beff0'
down_revision = '45592b7c4a13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_lense_user_id', sa.String(), nullable=True),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    ### end Alembic commands ###
