"""empty message

Revision ID: 56a6e00faec8
Revises: 3713c13beff0
Create Date: 2015-08-10 21:01:51.205493

"""

# revision identifiers, used by Alembic.
revision = '56a6e00faec8'
down_revision = '3713c13beff0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ratings_movie_id'), 'ratings', ['movie_id'], unique=False)
    op.create_index(op.f('ix_ratings_movie_lense_user_id'), 'ratings', ['movie_lense_user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_movie_lense_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_movie_id'), table_name='ratings')
    ### end Alembic commands ###
